<?php

/*
 * This file is part of EC-CUBE
 *
 * Copyright(c) EC-CUBE CO.,LTD. All Rights Reserved.
 *
 * http://www.ec-cube.co.jp/
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Customize\Repository;

use Twilio\Rest\Client;
use Customize\Entity\Reservation;
use Symfony\Bridge\Doctrine\RegistryInterface;

/**
 * BaseInfoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReservationRepository extends \Eccube\Repository\AbstractRepository
{
    /**
     * BaseInfoRepository constructor.
     *
     * @param RegistryInterface $registry
     */
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, Reservation::class);
    }

    public function getQueryBuilderBySearchData($searchData)
	{
		$qb = $this->createQueryBuilder('r')
			->select('r');


		return $qb;
    }

    /**
     * @param $Reservation
     */
    public function save($Reservation)
    {
        $em = $this->getEntityManager();
        $em->persist($Reservation);
        $em->flush($Reservation);
    }

    /**
     * @param $telephone 店舗の電話番号
     * @param $Reservation 予約情報
     * @param $rsv 予約true/キャンセルfalse
     */
    public function twilioSet($telephone, $Reservation, $rsv = false)
    {
        // Twilio アカウント情報
        $account_sid = env('TWILIO_SID');
        $auth_token = env('TWILIO_TOKEN');

        // A Twilio number you own with SMS capabilities
        $twilio_number = env('TWILIO_NUMBER');
        $shop_number = '+81'. substr($telephone, 1);

        try {

            $client = new Client($account_sid, $auth_token);

            $client->calls->create(
                // 電話
                $shop_number,
                $twilio_number,
                [
                    'twiml' => $this->getCallBody($Reservation, $rsv)
                ]
            );
        } catch (\Exception $e) {

            exit(var_dump($e));
            throw new \Exception("予約情報の発信は失敗になりました。");
        }
    }

    // メール本文
    public function getCallBody($Reservation, $rsv)
    {
        return $body = 
            '<Response><Say language="ja-jp" voice="woman">こちらはリローズ予約システムです。お客様からの来店の'
            . (!$rsv ? 'キャンセル' : 'ご予約')
            . 'をお知らせします。'
            . 'メニューID：'. $Reservation->getMenu()->getId()
            . '。メニュー名:'. $Reservation->getMenu()->getTitle()
            . '。来店日時:'. date('Y年m月d日 H時i分', strtotime($Reservation->getStarttime()))
            . '。お客様名:'. $Reservation->getCustomer()->getName01(). $Reservation->getCustomer()->getName02(). '様'
            . '。連絡先:'. $Reservation->getCustomer()->getPhoneNumber()
            . '</Say></Response>';
    }
}
